openapi: 3.0.0
paths:
  /:
    get:
      operationId: AppController_getHello
      parameters: []
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AppServiceType'
      summary: Get sample data
      tags:
        - App
info:
  title: Cats example
  description: The cats API description
  version: '1.0'
  contact: {}
tags: []
servers: []
components:
  schemas:
    AppServiceType:
      type: object
      properties:
        message:
          type: string
      required:
        - message
