openapi: 3.0.0
paths:
  /:
    get:
      operationId: AppController_getHello
      parameters: []
      responses:
        '200':
          description: Success
      summary: Get sample data
      tags:
        - App
info:
  title: Cats example
  description: The cats API description
  version: '1.0'
  contact: {}
tags: []
servers: []
components:
  schemas: {}
